## 模組/套件（package）
第三方寫好的函式集，有點像是外掛或是補丁

可以提供很強大跟快速的功能

有許多常用的套件已經內建在anaconda裡

未來如果需要新的套件則需要先在anaconda內安裝才能導入到notebook裡

## [Numpy](http://www.numpy.org/)

Numpy是在python內做數學/科學運算的套件


除了一個常用的數學運算函式之外，還有非常重要的n維陣列（np.array)的功能

np.array看起來很像list，但是他只能存放數字，而且有很多針對數字跟陣列運算的功能是list本身沒有的

導入套件

In [1]:
#導入套件的時候可以用 as ... 縮寫套件名稱
import numpy
import numpy as np

**np.array** 用把提供的資料建立成陣列（可以提供list）

In [59]:
M = np.array([1, 2, 3, 4, 5])
M

array([1, 2, 3, 4, 5])

也可以提供nested list

In [64]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### numpy operation v.s.list opteration

In [7]:
a = np.array([1,2,3])
b = [1,2,3]
print(a*2)
print(b*2)

[2 4 6]
[1, 2, 3, 1, 2, 3]


In [8]:
print(a**2)  #np.array可以執行
print(b**2)  #一般的list會跳錯誤

[1 4 9]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

**np.arange ( )** 類似 range ( ) 的函數

In [9]:
print(np.arange(10))
list(range(10))

[0 1 2 3 4 5 6 7 8 9]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
#例題
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [1]:
#演練
#用np.arange製作出 array([100, 90, 80, 70, 60, 50])

**其他製作numpy array的基本作法** 

In [62]:
a = np.zeros((2,2))   # 全部都是零
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2,5))    # 全部都是一
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # 全部都是指定的數字
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(5)         # 單位矩陣（可以跳過）
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[0. 0.]
 [0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[7 7]
 [7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### slicing:跟list一樣，但這邊會多介紹一個細節
取出第一列

In [65]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
M[0]

array([1, 2, 3])

取出第 3 列，第 2 , 3 行的資料

In [69]:
M[2, 1:]

array([8, 9])

取出所有列，第 2, 3 行的資料

In [70]:
#例題
M[0:3, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [2]:
#演練
#取出第1,2行的第1,2列

## 練習題（答案在這份檔案最下方）

In [ ]:
#1.宣告一個變數Q1，它是一個(3,3)所有值都為零的陣列

In [21]:
#2.用slicing的方式取出no2_list裡的8
no2_list=np.array([[5,0,2],[[8,3],1],[0,9,7,3]])

In [25]:
#3.建立一個5x5大小的矩陣，其中在斜線上（1之1,2之2....)的數值為7,其他數值為0

In [35]:
#4.製作一個np.array，其中的數值為0~10的平方

In [37]:
#5.用slicing的方式取出no5_list裡的[2,3,4,5,6]
no5_list = [0,0,1,2,3,4,5,6,3,2,1,1,0]

## 回家作業

#### 第一題  建立一個大小為5x6的矩陣no1_array，其中的值皆為1


#### 第二題  建立矩陣no2_array，讓其中的值為[9,8,7,6,5,4,3,2,1]

#### 第三題  用slicing的方式將no3_array裡的各個項目倒序取出 [72,42,20,6,0]

In [47]:
no3_array = np.arange(0,10,2)*np.arange(1,11,2)
no3_array

array([ 0,  6, 20, 42, 72])

#### 第四題 取出第3,4行的每一列   ans包含: 3, 4, 7, 8, 11, 12, 15, 16

In [49]:
no4_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
no4_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 第五題 建立一個5x5大小的矩陣no5_array，其中在斜線上（1之1,2之2....)的數值為7,其他數值為3

## 練習題答案

In [31]:
#1.宣告一個變數Q1，它是一個(3,3)所有值都為零的陣列
Q1=np.zeros((3,3))
Q1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#2.用slicing的方式取出no2_list裡的8
no2_list=np.array([[5,0,2],[[8,3],1],[0,9,7,3]])
no2_list[1][0][0]

8

In [30]:
#3.建立一個5x5大小的矩陣Q2，其中在斜線上（1之1,2之2....)的數值為7,其他數值為0
Q2 = np.full((5,5),7) * np.eye(5)
Q2

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

In [39]:
#4.製作一個np.array Q3，其中的數值為0~10的平方
Q3 = np.arange(0,11)**2
Q3

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [38]:
#5.用slicing的方式取出no5_list裡的[2,3,4,5,6]
no5_list = [0,0,1,2,3,4,5,6,3,2,1,1,0]
no5_list[3:8]

[2, 3, 4, 5, 6]