## Numpy part2
#### 各種不同numpy函式

所有內容包含：
- **.shape** 檢查矩陣的尺寸/形狀
- **np.mean()** 將陣列裡的數字取平均
- **np.sum()** 將陣列裡的數字加總
- **np.max ()** 取出陣列中最大值
- **np.argmax ()** 找出陣列中最大值的位置
- **np.random.random** 指定特定shape的大小，用亂數值將它填滿
- **np.random.randint** 可以指定數值大小跟形狀，並用符合區間的亂數的正整數填滿
- np.array比大小
- 更改np.array的數值
- **.reshape()** : 改變np.array的形狀
- -1在reshape時的含義
- **np.append()** :加入一個item到np.array裡
- **np.concatenate()** :合併兩個np.array
- **np.delete()** :刪除項目(index而非value）

In [92]:
import numpy as np

In [93]:
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
K = np.array([1,2,3,4,5])

### .shape ：檢查陣列的尺寸/形狀

In [56]:
M.shape, K.shape

((3, 3), (5,))

### np.mean ( ) 將陣列裡的數字取平均

In [57]:
#例題
np.mean(np.arange(10))

4.5

In [95]:
#演練
#製作一個長度大於5的np.array，並計算他的平均值

7878.166666666667

### np.sum ( ) 將陣列裡的數字加總

In [96]:
np.sum(np.arange(10))

45

In [60]:
print(sum(M))
print(np.sum(M))

[12 15 18]
45


### np.max () 取出陣列中最大值

In [13]:
np.max([2,5,1,3,2,10,2])

10

### np.argmax () 找出陣列中最大值的位置

In [97]:
print(np.argmax([2,5,1,3,2,10,2]))

5


In [98]:
#例題
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.argmax(M))
print(M[2])
print(M[2,2])
## [8//3,8%3]

8
[7 8 9]
9


In [100]:
#演練
K=np.array([1230,32,4324,123,232,312031])
#找出K的最大值的位置，並回傳他前一項的數值

232

### np.random.random 指定特定shape的大小，用亂數值將它填滿

In [158]:
M = np.random.random(size=(3,3))
M

array([[0.48128909, 0.28972871, 0.46258023],
       [0.50299193, 0.42966439, 0.20840471],
       [0.71822947, 0.89074413, 0.53093465]])

### np.random.randint 可以指定數值大小跟形狀，並用符合區間的亂數的正整數填滿

In [152]:
np.random.randint(0,10,(2,2))

array([[4, 9],
       [3, 4]])

### 特殊np.array功能
直接對np.array應用判斷式選出 e.x.M 矩陣中大於 3 的元素

In [154]:
M>0.5

array([[ True, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [155]:
#例題
M[M>0.5]

array([0.89823052, 0.92538348, 0.64482573, 0.90954248])

In [160]:
#演練
M = np.random.random(size=(3,3))
M = np.round(M*10)
print(M)
#找出M陣列中所有偶數的項目

[[3. 7. 1.]
 [2. 4. 5.]
 [8. 4. 2.]]


array([2., 4., 8., 4., 2.])

### 可以任意更改np.array裡面的數值

In [161]:
M[0][0]=100
M

array([[100.,   7.,   1.],
       [  2.,   4.,   5.],
       [  8.,   4.,   2.]])

In [162]:
M[M>5]=0
M

array([[0., 0., 1.],
       [2., 4., 5.],
       [0., 4., 2.]])

### .reshape() : 改變np.array的形狀

In [164]:
a = np.arange(30)
print(a.reshape((10,3)))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


或是直接指定.shape的結果也可以達到一樣的效果

In [166]:
a.shape = (3,10)

In [167]:
# a.shape = (3,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

#### -1 在np.array的shape應用時有很特別的用途，代表的是任何需要的數值（被動值） 

In [169]:
#範例
a.shape = (5,3,-1)
print(a.shape)
a

(5, 3, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]]])

In [170]:
#演練
#將a改成形狀為(15,2,1)的陣列

(15, 2, 1)

### np.append() :加入一個item到np.array裡

In [171]:
np.append(K,10)

array([  1230,     32,   4324,    123,    232, 312031,     10])

In [174]:
np.append(M,[[2,3,4]],axis=0)

array([[0., 0., 1.],
       [2., 4., 5.],
       [0., 4., 2.],
       [2., 3., 4.]])

In [175]:
np.append(M,[[2],[3],[4]],axis=1)

array([[0., 0., 1., 2.],
       [2., 4., 5., 3.],
       [0., 4., 2., 4.]])

### np.concatenate() :合併兩個np.array

In [46]:
np.concatenate((M,M),axis=0)

array([[0., 5., 0.],
       [0., 1., 0.],
       [4., 0., 0.],
       [0., 5., 0.],
       [0., 1., 0.],
       [4., 0., 0.]])

In [47]:
print(np.concatenate((M,M),axis=0).shape)
print(np.concatenate((M,M),axis=1).shape)

(6, 3)
(3, 6)


In [48]:
np.concatenate((M,M),axis=0)

array([[0., 5., 0.],
       [0., 1., 0.],
       [4., 0., 0.],
       [0., 5., 0.],
       [0., 1., 0.],
       [4., 0., 0.]])

In [49]:
np.concatenate((M,M),axis=1)

array([[0., 5., 0., 0., 5., 0.],
       [0., 1., 0., 0., 1., 0.],
       [4., 0., 0., 4., 0., 0.]])

#### concatenate跟append的用法
基本上可以隨機替換，但使用的難易度在不同情況會不一樣

append:一維陣列的時候比較適合應用

concatenate:多維陣列的時候使用

### np.delete() :刪除項目(index而非value）

In [176]:
K = np.array([1,3,5,7,9])
K = np.delete(K,3)
K

array([1, 3, 5, 9])

## 練習題（答案在這份檔案最下方）

In [37]:
#Q1找出Q1的最大值跟最小值
Q1 = np.random.randint(1,100,(5,5))

In [33]:
#Q2用 np.random.random 宣告一個變數Q2，x的shape為5x6的陣列 Hint：(5,6)

In [34]:
#Q3 把Q2改成(30,)的形狀

In [71]:
#Q4. 用零取代Q2中的最小值和最大值

In [ ]:
#Q5 找出Q5最大值的「索引位置」
Q5 = np.random.randint(1,100,(5,5))

In [ ]:
#Q6 用np.random.randint製作一個Q6，shape為(5,)，其中最大值為50、最小值為7

In [ ]:
#Q7 用np.random.randint製作一個Q7，shape為(5,)，其中最大值為50、平均為22

In [ ]:
#Q8 將Q8內所有偶數改為零
Q8 = np.random.randint(1,100,(5,5))

In [ ]:
#Q9 用 np.random.random 做出Q9，其中的依序為[1,5,2,4,3]

In [39]:
#Q10 合併Q10_1跟Q10_2
Q10_1 = np.random.randint(1,100,(2,2))
Q10_2 = np.random.randint(1,100,(1,2))

## 回家作業

#### 第一題 no1_array最小值的「位置」


In [44]:
no1_array = np.random.randint(1,100,30)

#### 第二題  用 np.random.randint 做出no2_array，shape為（3,3），其中第一維度上每一組值的平均分別為3,4,5

#### 第三題  找出no3_array的第二大值

In [46]:
no3_array = np.random.randint(1,1000,20)

#### 第四題  數學上有個叫cumulative sum的概念，是依序將各個項目加起來 
#### e.x. [1,2,3,4,5,6,7]  >> cumulative sum為 [1,3,6,10,15,21,28]
#### 在不用numpy內建的cumulative sum函式下，製作一個no4_cumsum其中的值為no4_array的cumulative sum

In [42]:
no4_array=np.random.randint(10,20,20)

#### 第五題  用 np.random.randint 做出no5_array，shape為（5,6），其中至少包含3個3、4個4、5個5

## 練習題答案

In [67]:
#Q1找出Q1的最大值跟最小值
Q1 = np.random.randint(1,100,(5,5))
np.max(Q1),np.min(Q1)

(98, 14)

In [68]:
#Q2用 np.random.random 宣告一個變數Q2，x的shape為5x6的陣列 Hint：(5,6)
Q2 = np.random.random((5,6))
Q2

array([[7.05226549e-05, 2.17012295e-02, 7.02907606e-01, 6.82664488e-01,
        9.04294291e-01, 7.96645907e-02],
       [9.70791217e-01, 7.78914187e-01, 8.08808502e-02, 6.44073552e-01,
        3.67409188e-01, 1.31652309e-01],
       [2.89321604e-01, 5.58164814e-01, 7.69542952e-01, 5.59829767e-01,
        1.55123216e-01, 5.30438094e-01],
       [8.72809104e-01, 8.94685459e-01, 1.04250422e-01, 6.35243817e-01,
        1.58258039e-01, 5.84990824e-01],
       [4.29397292e-01, 8.08905091e-01, 8.91699518e-02, 8.38062142e-01,
        6.38166042e-01, 3.32801816e-01]])

In [69]:
#Q3 把Q2改成(30,)的形狀
Q2 = Q2.reshape((30,))
Q2.shape

(30,)

In [70]:
#Q4. 用零取代Q2中的最小值和最大值
Q2[np.argmin(Q2)]=0
Q2[np.argmax(Q2)]=0
Q2

array([0.        , 0.02170123, 0.70290761, 0.68266449, 0.90429429,
       0.07966459, 0.        , 0.77891419, 0.08088085, 0.64407355,
       0.36740919, 0.13165231, 0.2893216 , 0.55816481, 0.76954295,
       0.55982977, 0.15512322, 0.53043809, 0.8728091 , 0.89468546,
       0.10425042, 0.63524382, 0.15825804, 0.58499082, 0.42939729,
       0.80890509, 0.08916995, 0.83806214, 0.63816604, 0.33280182])

In [74]:
#Q5 找出Q5最大值的「索引位置」
Q5 = np.random.randint(1,100,(5,5))
np.max(Q5),Q5[np.argmax(Q5)//5,np.argmax(Q5)%5]

(93, 93)

In [76]:
#Q6 用np.random.randint製作一個Q6，shape為(5,)，其中最大值為50、最小值為7
correct = False
while correct == False:
    Q6 = np.random.randint(5,60,(5,))
    if np.max(Q6)==50 and np.min(Q6)==7:
        correct = True
Q6
        

array([32, 24,  7, 50, 23])

In [78]:
#Q7 用np.random.randint製作一個Q7，shape為(5,)，其中最大值為50、平均為22
correct = False
while correct == False:
    Q7 = np.random.randint(5,60,(5,))
    if np.max(Q7)==50 and np.mean(Q7)==22:
        correct = True
Q7

array([ 7,  7, 41,  5, 50])

In [79]:
#Q8 將Q8內所有偶數改為零
Q8 = np.random.randint(1,100,(5,5))
Q8[Q8%2==0]=0
Q8

array([[ 0, 25, 15, 43,  0],
       [97,  0, 99, 75, 73],
       [33,  0,  0,  0, 11],
       [ 0,  0, 29, 73,  0],
       [ 0, 49,  0,  0,  0]])

In [85]:
Q9==[1,5,2,4,3]

array([False, False, False, False, False])

In [87]:
#Q9 用 np.random.random 做出Q9，其中的依序為[1,5,2,4,3]
correct = False
while correct == False:
    Q9 = np.random.randint(1,6,(5,))
    if np.sum(Q9==[1,5,2,4,3])==5:
        correct = True
Q9

array([1, 5, 2, 4, 3])

In [91]:
#Q10 合併Q10_1跟Q10_2
Q10_1 = np.random.randint(1,100,(2,2))
Q10_2 = np.random.randint(1,100,(1,2))
np.concatenate((Q10_1,Q10_2),axis=0)

array([[89, 87],
       [18, 31],
       [78, 89]])